language: php

sudo: required

php:
  - 7.1.8

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - sudo apt-get -qq update
  - mysql -e 'CREATE DATABASE dcas_l55_refactor;'


before_script:
  - travis_retry composer self-update
  - travis_retry composer install --dev --prefer-source --no-interaction
  - npm install
  - php artisan migrate

cache:
  directories:
    - node_modules
    - vendor

script:
  - node_modules/.bin/bower update
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - vendor/phpspec/phpspec/bin/phpspec run
  - vendor/bin/codecept build
  - vendor/bin/codecept run
  - vendor/bin/behat

services:
  - mysql
  - redis
  - sqlite3

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [[ $COMPOSER_FLAGS == '' ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi